name: CD

on:
  push:
    branches:
      - main # mainブランチへのpush時のみ実行

jobs:
  deploy-supabase:
    runs-on: ubuntu-latest
    # CIジョブが成功した場合のみ実行 (ci.ymlのジョブ名に合わせる)
    needs: [lint-type-test-build] # ci.yml のジョブ名と一致させる (存在する場合)
    if: github.event_name == 'push' && success() # needsジョブが成功した場合のみ

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest # または特定のバージョン

      - name: Link Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          # SUPABASE_PROJECT_ID は `supabase link --project-ref <project_id>` で取得し、Secretsに保存
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Deploy Supabase Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID

  deploy-aws-eks:
    runs-on: ubuntu-latest
    needs: [lint-type-test-build] # ci.yml のジョブ名と一致させる (存在する場合)
    if: github.event_name == 'push' && success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # 例: ap-northeast-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        # with: 
        #   version: 'latest' # or specific version

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f infra/k8s/fastapi-deploy.yaml
          kubectl apply -f infra/k8s/ingress.yaml
          # 必要に応じて他のマニフェストも適用
          # kubectl apply -f infra/k8s/hpa.yaml

  # submit-expo-eas: # モバイルアプリのビルドとストア提出 (必要に応じて有効化)
  #   runs-on: ubuntu-latest
  #   needs: [lint-type-test-build]
  #   if: github.event_name == 'push' && success()
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup pnpm
  #       uses: pnpm/action-setup@v2
  #       with:
  #         version: 8

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18.x'
  #         cache: 'pnpm'

  #     - name: Install dependencies
  #       run: pnpm install

  #     - name: Setup EAS CLI
  #       uses: expo/expo-github-action@v8
  #       with:
  #         eas-version: latest
  #         token: ${{ secrets.EXPO_TOKEN }}

  #     - name: Build and Submit to EAS
  #       run: |
  #         eas build --platform all --profile production --non-interactive --auto-submit
  #         # または特定のプラットフォームのみ
  #         # eas submit -p android --latest --profile production
  #         # eas submit -p ios --latest --profile production
